image: ruby:2.4.2

stages:
- build
- test
- review
- stage
- production

.old-test:
  stage: test
  services:
  - mongo:latest
  before_script:
  - cd reddit
  - bundle install
  script:
  - ruby simpletest.rb

.tests:
  stage: test
  image: docker:20.10.11
  services:
  - mongo:latest

variables:
  DATABASE_URL: 'mongo:27017'

build_job:
  stage: build
  image: docker:20.10.11
  script:
  - docker build
      -f reddit/docker/Dockerfile
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      ./reddit

test_unit_job:
  extends: .tests
  script:
  - docker run --rm
      --env DATABASE_URL=$DATABASE_URL
      $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      ruby /app/simpletest.rb

test_integration_job:
  extends: .tests
  script:
  - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
  - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  image: docker:20.10.11
  script:
  - docker network create $CI_COMMIT_SHORT_SHA
  - docker run --rm -d
      --name mongo
      --network $CI_COMMIT_SHORT_SHA
      --network-alias mongo
      mongo:latest
  - docker run --rm -d
      -p 9292:9292
      --env DATABASE_URL=$DATABASE_URL
      --name $CI_COMMIT_SHORT_SHA
      --network $CI_COMMIT_SHORT_SHA
      $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  environment:
    on_stop: stop branch review
    action: start
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$DEPLOY_HOST:9292/
  only:
    - branches
  except:
    - master

stop branch review:
  stage: review
  image: docker:20.10.11
  when: manual
  script:
  - docker kill $CI_COMMIT_SHORT_SHA
  - docker kill mongo
  - docker network rm $CI_COMMIT_SHORT_SHA
  environment:
    action: stop
    name: branch/$CI_COMMIT_REF_NAME

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com
