---

- name: Install docker-ce
  hosts: docker_hosts
  become: true

  tasks:

  - name: Update packages
    apt:
      name:
      - "ca-certificates"
      - "curl"
      - "gnupg"
      - "lsb-release"
      state: present
      update_cache: yes
    tags: install

  - name: Add docker repo key
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present
    tags: install

  - name: Add docker repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      filename: "docker-ce"
      state: present
    tags: install

  - name: Install docker engine
    apt:
      name:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
      state: present
      update_cache: yes
    tags: install

  - name: Add users to docker group
    user:
      name: "{{ item }}"
      groups: "docker"
      append: yes
    loop: "{{ docker_users }}"
    tags: install

  - name: Relogin due user group changed
    meta:
      reset_connection
    tags: install
