FROM ruby:2.2
RUN apt-get update -qq && apt-get install -y build-essential

ARG APP_HOME=/app

WORKDIR $APP_HOME
COPY Gemfile* $APP_HOME/
RUN bundle install
COPY . $APP_HOME

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
