FROM ruby:2.2-alpine3.4

ARG APP_HOME=/app

WORKDIR $APP_HOME
COPY . $APP_HOME

RUN apk --no-cache add build-base \
    && gem install bundler:1.17.2 \
    && bundle install \
    && apk del build-base

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
