---

- name: Install docker-ce
  hosts:
  - gitlab_hosts
  - gitlab_runners
  become: yes

  tasks:

  - name: Update packages
    ansible.builtin.apt:
      name:
      - "ca-certificates"
      - "curl"
      - "gnupg"
      - "lsb-release"
      state: present
      update_cache: yes

  - name: Add docker repo key
    ansible.builtin.apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present

  - name: Add docker repo
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      filename: "docker-ce"
      state: present

  - name: Install docker engine
    ansible.builtin.apt:
      name:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
      state: present
      update_cache: yes

  - name: Add users to docker group
    ansible.builtin.user:
      name: "{{ item }}"
      groups: "docker"
      append: yes
    loop: "{{ docker_users }}"

  - name: Relogin due user group changed
    ansible.builtin.meta:
      reset_connection

  - name: Install python3-docker
    ansible.builtin.apt:
      name: "python3-docker"
      state: "present"
      update_cache: yes
