---

- name: Install GitLab-CE
  hosts: docker_hosts

  tasks:

  - name: Make folders
    become: true
    ansible.builtin.file:
      path: "{{ item }}"
      mode: "0755"
      owner: "{{ gitlab_user }}"
      group: "{{ gitlab_group }}"
      state: "directory"
    loop:
    - "/srv/gitlab/config"
    - "/srv/gitlab/logs"
    - "/srv/gitlab/data"

  - name: Run GitLab-CE container
    community.docker.docker_container:
      name: "web"
      image: "gitlab/gitlab-ce:latest"
      state: "started"
      hostname: "gitlab.example.com"
      restart_policy: "always"
      env:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://{{ ansible_host }}'
      published_ports:
      - "80:80"
      - "443:443"
      - "2222:22"
      volumes:
      - "/srv/gitlab/config:/etc/gitlab"
      - "/srv/gitlab/logs:/var/log/gitlab"
      - "/srv/gitlab/data:/var/opt/gitlab"
