---

- name: Install docker-ce
  hosts:
  - k8s_control_nodes
  - k8s_worker_nodes
  vars:
    docker_version: "5:19.03.15~3-0~ubuntu-focal"
    docker_users:
    - ubuntu
  become: yes

  tasks:

  - name: Update packages
    ansible.builtin.apt:
      name:
      - "ca-certificates"
      - "curl"
      - "gnupg"
      - "lsb-release"
      state: present
      update_cache: yes

  - name: Add docker repo key
    ansible.builtin.apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present

  - name: Add docker repo
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      filename: "docker-ce"
      state: present

  - name: Install docker engine
    ansible.builtin.apt:
      name:
      - "docker-ce={{ docker_version }}"
      - "docker-ce-cli={{ docker_version }}"
      - "containerd.io"
      state: present
      update_cache: yes

  - name: Create docker config directory
    ansible.builtin.file:
      path: /etc/docker
      state: directory

  - name: Create docker config
    ansible.builtin.copy:
      dest: /etc/docker/daemon.json
      content: |
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2"
        }
    notify:
    - Restart docker

  - name: Add users to docker group
    ansible.builtin.user:
      name: "{{ item }}"
      groups: "docker"
      append: yes
    loop: "{{ docker_users }}"

  - name: Relogin due user group changed
    ansible.builtin.meta:
      reset_connection

  handlers:

  - name: Restart docker
    ansible.builtin.systemd:
      name: docker
      state: restarted
