version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
    - post_db:/data/db
    networks:
    - back_net
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.2
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
    - ${UI_PORT:-9292}:9292/tcp
    networks:
    - front_net
    depends_on:
    - post
    - comment
  post:
    build:
      context: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
    - front_net
    - back_net
    depends_on:
    - post_db
  comment:
    build:
      context: ./comment
      dockerfile: Dockerfile.2
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
    - front_net
    - back_net
    depends_on:
    - post_db

volumes:
  post_db:

networks:
  front_net:
  back_net:
